FROM debian:trixie

RUN apt-get update && apt-get -y --no-install-recommends install \
	cmake \
	g++-14 \
	git \
	kmod \
	libc6-dev \
	libelf-dev \
	make \
	pkg-config \
	clang \
	llvm \
	&& apt-get clean

# Starting from kernel 6.12.16, pahole seems to be required
RUN ln -sf /usr/bin/true /usr/bin/pahole

ADD builder-entrypoint.sh /
WORKDIR /build/probe
ENTRYPOINT [ "/builder-entrypoint.sh" ]

