FROM debian/eol:jessie

RUN sed -i -e 's/deb.debian.org/archive.debian.org\/debian-archive/g' /etc/apt/sources.list && \
    sed -i -e 's/security.debian.org/archive.debian.org\/debian-archive/g' /etc/apt/sources.list && \
    sed -i '/jessie-updates/d' /etc/apt/sources.list && \
    apt-get update && apt-get -y --no-install-recommends install \
	cmake \
	g++ \
	git \
	kmod \
	libc6-dev \
	libelf-dev \
	make \
	pkg-config \
	&& apt-get clean

ADD builder-entrypoint.sh /
WORKDIR /build/probe
ENTRYPOINT [ "/builder-entrypoint.sh" ]

