FROM ubuntu:noble

# Note: as of Feb-2026, ubuntu noble (without proposed) returns:
# $ apt list -a gcc-14
# gcc-14/noble-updates 14.2.0-4ubuntu2~24.04.1 amd64
# gcc-14/noble-security 14.2.0-4ubuntu2~24.04 amd64
# gcc-14/noble 14-20240412-0ubuntu1 amd64

RUN \
	apt-get update && \
	apt-get -y --no-install-recommends install \
		cmake \
		g++-14 \
		git \
		kmod \
		libc6-dev \
		libelf-dev \
		make \
		pkg-config \
		clang-14 \
		llvm-14 \
		&& apt-get clean

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 14 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 14

# Enforce usage of clang 14, since clang 15 seems to
# raise a lot of verifier issues
ENV CLANG clang-14
ENV LLC llc-14

ADD builder-entrypoint.sh /
WORKDIR /build/probe
ENTRYPOINT [ "/builder-entrypoint.sh" ]

