FROM ubuntu:noble

# Note: as of Feb-2026, ubuntu noble (without proposed) returns:
# $ apt list -a gcc-13
# gcc-13/noble-updates 13.3.0-6ubuntu2~24.04.1 amd64
# gcc-13/noble-security 13.3.0-6ubuntu2~24.04 amd64
# gcc-13/noble 13.2.0-23ubuntu4 amd64

RUN for pkg in g++-13* gcc-13* cpp-13* libgcc-13-dev libobjc-13-dev libstdc++-13-dev; do \
	echo "Package: $pkg\nPin: version 13.3.*\nPin-Priority: 900\n" \
	>> /etc/apt/preferences.d/pin-gcc; done

RUN \
	apt-get update && \
	apt-get -y --no-install-recommends install \
		cmake \
		g++-13/noble-updates \
		git \
		kmod \
		libc6-dev \
		libelf-dev \
		make \
		pkg-config \
		clang-14 \
		llvm-14 \
		&& apt-get clean

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 13 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 13

# Enforce usage of clang 14, since clang 15 seems to
# raise a lot of verifier issues
ENV CLANG clang-14
ENV LLC llc-14

ADD builder-entrypoint.sh /
WORKDIR /build/probe
ENTRYPOINT [ "/builder-entrypoint.sh" ]

