FROM fedora:31

ADD https://github.com/multiarch/qemu-user-static/releases/download/v7.0.0-7/qemu-x86_64-static.tar.gz /usr/bin/

RUN yum -y install \
	wget \
	git \
	gcc \
	gcc-c++ \
	autoconf \
	bison \
	flex \
	make \
	cmake \
	elfutils-devel \
	findutils \
	kmod \
	clang \
	llvm \
	python-lxml && yum clean all

ADD builder-entrypoint.sh /
WORKDIR /build/probe
ENTRYPOINT [ "/builder-entrypoint.sh" ]
